{% set version = '0.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shiny.fluent
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shiny.fluent_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shiny.fluent/shiny.fluent_{{ version }}.tar.gz
  sha256: 74f25df5cc664b4b5f35e75de4d36b8f91331ff3936cb43a03668df799509891

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools
    - r-jsonlite
    - r-rlang
    - r-shiny
    - r-shiny.react >=0.3.0
  run:
    - r-base
    - r-htmltools
    - r-jsonlite
    - r-rlang
    - r-shiny
    - r-shiny.react >=0.3.0

test:
  commands:
    - $R -e "library('shiny.fluent')"           # [not win]
    - "\"%R%\" -e \"library('shiny.fluent')\""  # [win]

about:
  home: https://appsilon.github.io/shiny.fluent/, https://github.com/appsilon/shiny.fluent
  license: LGPL-3.0-only
  summary: A rich set of UI components for building Shiny applications, including inputs, containers,
    overlays, menus, and various utilities. All components from Fluent UI (the underlying
    JavaScript library) are available and have usage examples in R.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
