{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-shiny.fluent
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shiny.fluent_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shiny.fluent/shiny.fluent_{{ version }}.tar.gz
  sha256: 3a0809a7cc9167cd5f3d570cd75526ff7b14e489f4d3fe3d5c7c9b7d5511c934

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools
    - r-jsonlite
    - r-rlang
    - r-shiny
    - r-shiny.react >=0.4.0
  run:
    - r-base
    - r-htmltools
    - r-jsonlite
    - r-rlang
    - r-shiny
    - r-shiny.react >=0.4.0

test:
  commands:
    - $R -e "library('shiny.fluent')"           # [not win]
    - "\"%R%\" -e \"library('shiny.fluent')\""  # [win]

about:
  home: https://appsilon.github.io/shiny.fluent/
  dev_url: https://github.com/appsilon/shiny.fluent
  license: LGPL-3.0-only
  summary: A rich set of UI components for building Shiny applications, including inputs, containers, overlays, menus, and various utilities. All components from Fluent UI (the underlying JavaScript library) are available and have usage examples in R.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
